type User {
  _id: String!
  name: String
}

type Resource {
  _id: String!
  text: String
  owner: User
}

type Query {
  findUser(name:String, _id:String): User
  findUsers(name:String): [User]
  findResource(_id:String): Resource
  findResources(text:String): [Resource]
  findResourcesByUser(_id:String!): [Resource]
}

type Mutation {
  addUser(name:String!): User
  addResource(text:String!): Resource
  setResourceOwner(user:String!, resource:String!): Boolean
  removeResourceOwner(_id:String!): Boolean
}
